version: '2'
services:

  app:
#    build:
#      context: .
    image: conflabs/php-dev:latest
    container_name: app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  db:
    container_name: db
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=chicken
      - MYSQL_DATABASE=tvsc
      - MYSQL_USER=mysqladmin
      - MYSQL_PASSWORD=BIF420^inyoface

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db